---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: Configure Git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name | default('Your Name') }}"
  when: git_user_name is defined

- name: Configure Git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email | default('your.email@example.com') }}"
  when: git_user_email is defined

- name: Prompt for Git user.name if not set
  ansible.builtin.pause:
    prompt: "Enter your Git user.name"
  register: git_name_input
  when: git_user_name is not defined

- name: Set Git user.name from input
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_name_input.user_input }}"
  when: git_user_name is not defined

- name: Prompt for Git user.email if not set
  ansible.builtin.pause:
    prompt: "Enter your Git user.email"
  register: git_email_input
  when: git_user_email is not defined

- name: Set Git user.email from input
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email_input.user_input }}"
  when: git_user_email is not defined
