---
- name: "Ghostty | {{ ansible_distribution }} | Install dependencies"
  ansible.builtin.apt:
    name:
      - libgtk-4-dev
      - libadwaita-1-dev
      - git
      - curl
      - wget
    state: present
  become: true

- name: "Ghostty | {{ ansible_distribution }} | Build and install Ghostty"
  block:
    - name: "Ghostty | Create temp directory"
      ansible.builtin.tempfile:
        state: directory
        suffix: ghostty
      register: ghostty_temp_dir

    - name: "Ghostty | Download Zig 0.13"
      ansible.builtin.get_url:
        url: "https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz"
        dest: "{{ ghostty_temp_dir.path }}/zig.tar.xz"
        mode: "0644"

    - name: "Ghostty | Extract Zig"
      ansible.builtin.unarchive:
        src: "{{ ghostty_temp_dir.path }}/zig.tar.xz"
        dest: "{{ ghostty_temp_dir.path }}"
        remote_src: true

    - name: "Ghostty | Clone Ghostty repository"
      ansible.builtin.git:
        repo: "https://github.com/ghostty-org/ghostty.git"
        dest: "{{ ghostty_temp_dir.path }}/ghostty"
        version: "v1.0.0"

    - name: "Ghostty | Build Ghostty"
      ansible.builtin.command:
        cmd: "{{ ghostty_temp_dir.path }}/zig-linux-x86_64-0.13.0/zig build -p {{ ansible_user_dir }}/.local -Doptimize=ReleaseFast"
        chdir: "{{ ghostty_temp_dir.path }}/ghostty"
      become: false

    - name: "Ghostty | Update desktop database"
      ansible.builtin.command: update-desktop-database {{ ansible_user_dir }}/.local/share/applications
      become: false
      ignore_errors: true

    - name: "Ghostty | Create symlink to /usr/local/bin"
      ansible.builtin.file:
        src: "{{ ansible_user_dir }}/.local/bin/ghostty"
        dest: "/usr/local/bin/ghostty"
        state: link
      become: true
      ignore_errors: true

  always:
    - name: "Ghostty | Clean up temp directory"
      ansible.builtin.file:
        path: "{{ ghostty_temp_dir.path }}"
        state: absent
      when: ghostty_temp_dir is defined