---
- name: "Ghostty | {{ ansible_distribution }} | Download and install Ghostty"
  block:
    - name: "Ghostty | Create temp directory"
      ansible.builtin.tempfile:
        state: directory
        suffix: ghostty
      register: ghostty_temp_dir

    - name: "Ghostty | Download Ghostty AppImage"
      ansible.builtin.get_url:
        url: "https://release.files.ghostty.org/ghostty-1.0.1-x86_64.AppImage"
        dest: "{{ ghostty_temp_dir.path }}/ghostty.AppImage"
        mode: "0755"

    - name: "Ghostty | Install Ghostty to /usr/local/bin"
      ansible.builtin.copy:
        src: "{{ ghostty_temp_dir.path }}/ghostty.AppImage"
        dest: "/usr/local/bin/ghostty"
        mode: "0755"
        remote_src: true
      become: true

    - name: "Ghostty | Create desktop entry"
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Type=Application
          Name=Ghostty
          Comment=A fast, feature-rich, and cross-platform terminal emulator
          Exec=/usr/local/bin/ghostty
          Icon=utilities-terminal
          Terminal=false
          Categories=System;TerminalEmulator;
        dest: "/usr/share/applications/ghostty.desktop"
        mode: "0644"
      become: true

  always:
    - name: "Ghostty | Clean up temp directory"
      ansible.builtin.file:
        path: "{{ ghostty_temp_dir.path }}"
        state: absent
      when: ghostty_temp_dir is defined